import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hoque_family_chores/domain/entities/task.dart';
import 'package:hoque_family_chores/domain/value_objects/user_id.dart';
import 'package:hoque_family_chores/domain/value_objects/task_id.dart';
import 'package:hoque_family_chores/domain/value_objects/points.dart';
import 'package:hoque_family_chores/presentation/providers/riverpod/auth_notifier.dart';
import 'package:hoque_family_chores/presentation/providers/riverpod/family_notifier.dart';
import 'package:hoque_family_chores/presentation/providers/riverpod/task_list_notifier.dart';
import 'package:hoque_family_chores/utils/logger.dart';

/// Shows a bottom sheet for quickly adding a new quest/task
void showQuickAddQuestSheet(BuildContext context) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (context) => const QuickAddQuestSheet(),
  );
}

/// Quick Add Quest bottom sheet widget
class QuickAddQuestSheet extends ConsumerStatefulWidget {
  const QuickAddQuestSheet({super.key});

  @override
  ConsumerState<QuickAddQuestSheet> createState() => _QuickAddQuestSheetState();
}

class _QuickAddQuestSheetState extends ConsumerState<QuickAddQuestSheet> {
  final _logger = AppLogger();
  final _titleController = TextEditingController();
  final _titleFocusNode = FocusNode();
  
  int _selectedStars = 3;
  UserId? _selectedAssignee;
  DateTime? _selectedDueDate;
  bool _isLoading = false;

  // Template tasks
  final List<_TemplateTask> _templates = [
    _TemplateTask(emoji: '🧹', title: 'Kitchen', stars: 5),
    _TemplateTask(emoji: '🍽️', title: 'Dishes', stars: 3),
    _TemplateTask(emoji: '🛏️', title: 'Bed', stars: 3),
    _TemplateTask(emoji: '📚', title: 'Homework', stars: 8),
    _TemplateTask(emoji: '🗑️', title: 'Bins', stars: 3),
  ];

  @override
  void initState() {
    super.initState();
    // Autofocus the title field after a short delay
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _titleFocusNode.requestFocus();
    });
    
    // Set default due date to today at 6pm
    final now = DateTime.now();
    _selectedDueDate = DateTime(now.year, now.month, now.day, 18, 0);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _titleFocusNode.dispose();
    super.dispose();
  }

  void _applyTemplate(_TemplateTask template) {
    setState(() {
      _titleController.text = template.title;
      _selectedStars = template.stars;
    });
  }

  TaskDifficulty _getDifficultyFromStars(int stars) {
    if (stars <= 3) return TaskDifficulty.easy;
    if (stars <= 5) return TaskDifficulty.medium;
    if (stars <= 8) return TaskDifficulty.hard;
    return TaskDifficulty.challenging;
  }

  Future<void> _addQuest() async {
    if (_titleController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a task title')),
      );
      return;
    }

    if (_selectedDueDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a due date')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final authState = ref.read(authNotifierProvider);
      final currentUser = authState.user;
      
      if (currentUser == null) {
        throw Exception('User not logged in or not part of a family');
      }

      final notifier = ref.read(taskListNotifierProvider(currentUser.familyId).notifier);
      
      // Create a temporary task object to pass to createTask
      await notifier.createTask(
        Task(
          id: TaskId(''), // Will be generated by backend
          title: _titleController.text.trim(),
          description: '', // Quick add doesn't include description
          status: _selectedAssignee != null ? TaskStatus.assigned : TaskStatus.available,
          difficulty: _getDifficultyFromStars(_selectedStars),
          dueDate: _selectedDueDate!,
          assignedToId: _selectedAssignee,
          createdById: currentUser.id,
          createdAt: DateTime.now(),
          points: Points(_selectedStars),
          tags: [],
          familyId: currentUser.familyId,
        ),
      );

      _logger.i('Quick Add Quest: Successfully created task "${_titleController.text}"');

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Quest "${_titleController.text.trim()}" added! ⭐'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e, s) {
      _logger.e('Quick Add Quest: Error creating task', error: e, stackTrace: s);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error adding quest: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authNotifierProvider);
    final currentUser = authState.user;
    
    if (currentUser == null) {
      return Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
        padding: const EdgeInsets.all(24),
        child: const Text('Please log in and join a family to add quests.'),
      );
    }

    final familyMembersAsync = ref.watch(familyMembersNotifierProvider(currentUser.familyId));

    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      padding: EdgeInsets.only(
        left: 24,
        right: 24,
        top: 24,
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Header
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Quick Add Quest',
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
              IconButton(
                icon: const Icon(Icons.close),
                onPressed: () => Navigator.of(context).pop(),
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Template chips
          const Text(
            'Templates',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: Colors.grey,
            ),
          ),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: _templates.map((template) {
              return ActionChip(
                label: Text('${template.emoji} ${template.title} ${template.stars}⭐'),
                onPressed: () => _applyTemplate(template),
                backgroundColor: Colors.grey[100],
              );
            }).toList(),
          ),
          const SizedBox(height: 24),

          // Title field
          TextField(
            controller: _titleController,
            focusNode: _titleFocusNode,
            decoration: const InputDecoration(
              labelText: 'Quest Title',
              hintText: 'What needs to be done?',
              border: OutlineInputBorder(),
              prefixIcon: Icon(Icons.task_alt),
            ),
            textCapitalization: TextCapitalization.sentences,
            onSubmitted: (_) => _addQuest(),
          ),
          const SizedBox(height: 24),

          // Star selector
          const Text(
            'Difficulty / Stars',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: Colors.grey,
            ),
          ),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            children: [3, 5, 8, 10].map((stars) {
              final isSelected = _selectedStars == stars;
              return ChoiceChip(
                label: Text('$stars ⭐'),
                selected: isSelected,
                onSelected: (selected) {
                  if (selected) {
                    setState(() {
                      _selectedStars = stars;
                    });
                  }
                },
                selectedColor: const Color(0xFFFFB300),
                labelStyle: TextStyle(
                  color: isSelected ? Colors.white : Colors.black,
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                ),
              );
            }).toList(),
          ),
          const SizedBox(height: 24),

          // Assignee dropdown
          const Text(
            'Assign To (Optional)',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: Colors.grey,
            ),
          ),
          const SizedBox(height: 8),
          familyMembersAsync.when(
            data: (members) {
              return DropdownButtonFormField<UserId>(
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: 'Available to anyone',
                  prefixIcon: Icon(Icons.person),
                ),
                items: [
                  const DropdownMenuItem<UserId>(
                    value: null,
                    child: Text('Available to anyone'),
                  ),
                  ...members.map((member) {
                    return DropdownMenuItem<UserId>(
                      value: member.id,
                      child: Text(member.name),
                    );
                  }),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedAssignee = value;
                  });
                },
              );
            },
            loading: () => const LinearProgressIndicator(),
            error: (error, stack) => Text('Error loading family members: $error'),
          ),
          const SizedBox(height: 24),

          // Due date chips
          const Text(
            'Due Date',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: Colors.grey,
            ),
          ),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            children: [
              _buildDueDateChip('Today 6pm', _getTodayAt(18)),
              _buildDueDateChip('Today 8pm', _getTodayAt(20)),
              _buildDueDateChip('Tomorrow', _getTomorrowAt(18)),
            ],
          ),
          const SizedBox(height: 32),

          // Add button
          SizedBox(
            height: 50,
            child: ElevatedButton(
              onPressed: _isLoading ? null : _addQuest,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFFFFB300),
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
              child: _isLoading
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : const Text(
                      'Add Quest ⭐',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
            ),
          ),
        ],
      ),
    );
  }

  DateTime _getTodayAt(int hour) {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day, hour, 0);
  }

  DateTime _getTomorrowAt(int hour) {
    final now = DateTime.now();
    final tomorrow = now.add(const Duration(days: 1));
    return DateTime(tomorrow.year, tomorrow.month, tomorrow.day, hour, 0);
  }

  Widget _buildDueDateChip(String label, DateTime dateTime) {
    final isSelected = _selectedDueDate != null &&
        _selectedDueDate!.year == dateTime.year &&
        _selectedDueDate!.month == dateTime.month &&
        _selectedDueDate!.day == dateTime.day &&
        _selectedDueDate!.hour == dateTime.hour;

    return ChoiceChip(
      label: Text(label),
      selected: isSelected,
      onSelected: (selected) {
        if (selected) {
          setState(() {
            _selectedDueDate = dateTime;
          });
        }
      },
      selectedColor: const Color(0xFFFFB300),
      labelStyle: TextStyle(
        color: isSelected ? Colors.white : Colors.black,
        fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
      ),
    );
  }
}

/// Template task for quick add
class _TemplateTask {
  final String emoji;
  final String title;
  final int stars;

  _TemplateTask({
    required this.emoji,
    required this.title,
    required this.stars,
  });
}
