// Mocks generated by Mockito 5.4.6 from annotations
// in hoque_family_chores/test/domain/usecases/streak/update_streak_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hoque_family_chores/domain/entities/streak.dart' as _i2;
import 'package:hoque_family_chores/domain/entities/user.dart' as _i7;
import 'package:hoque_family_chores/domain/repositories/streak_repository.dart'
    as _i3;
import 'package:hoque_family_chores/domain/repositories/user_repository.dart'
    as _i6;
import 'package:hoque_family_chores/domain/value_objects/points.dart' as _i8;
import 'package:hoque_family_chores/domain/value_objects/user_id.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreak_0 extends _i1.SmartFake implements _i2.Streak {
  _FakeStreak_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StreakRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRepository extends _i1.Mock implements _i3.StreakRepository {
  MockStreakRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Streak?> getStreak(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, [userId]),
            returnValue: _i4.Future<_i2.Streak?>.value(),
          )
          as _i4.Future<_i2.Streak?>);

  @override
  _i4.Stream<_i2.Streak?> streamStreak(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#streamStreak, [userId]),
            returnValue: _i4.Stream<_i2.Streak?>.empty(),
          )
          as _i4.Stream<_i2.Streak?>);

  @override
  _i4.Future<void> createStreak(_i2.Streak? streak) =>
      (super.noSuchMethod(
            Invocation.method(#createStreak, [streak]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateStreak(_i2.Streak? streak) =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, [streak]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Streak> incrementStreak(
    _i5.UserId? userId,
    DateTime? completionDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#incrementStreak, [userId, completionDate]),
            returnValue: _i4.Future<_i2.Streak>.value(
              _FakeStreak_0(
                this,
                Invocation.method(#incrementStreak, [userId, completionDate]),
              ),
            ),
          )
          as _i4.Future<_i2.Streak>);

  @override
  _i4.Future<_i2.Streak> resetStreak(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#resetStreak, [userId]),
            returnValue: _i4.Future<_i2.Streak>.value(
              _FakeStreak_0(this, Invocation.method(#resetStreak, [userId])),
            ),
          )
          as _i4.Future<_i2.Streak>);

  @override
  _i4.Future<_i2.Streak> useFreeze(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#useFreeze, [userId]),
            returnValue: _i4.Future<_i2.Streak>.value(
              _FakeStreak_0(this, Invocation.method(#useFreeze, [userId])),
            ),
          )
          as _i4.Future<_i2.Streak>);

  @override
  _i4.Future<_i2.Streak> purchaseFreeze(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseFreeze, [userId]),
            returnValue: _i4.Future<_i2.Streak>.value(
              _FakeStreak_0(this, Invocation.method(#purchaseFreeze, [userId])),
            ),
          )
          as _i4.Future<_i2.Streak>);

  @override
  _i4.Future<void> awardMilestoneBonus(
    _i5.UserId? userId,
    int? milestoneDay,
    int? starAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#awardMilestoneBonus, [
              userId,
              milestoneDay,
              starAmount,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i6.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.User?> getUserProfile(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i7.User?>.value(),
          )
          as _i4.Future<_i7.User?>);

  @override
  _i4.Stream<_i7.User?> streamUserProfile(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#streamUserProfile, [userId]),
            returnValue: _i4.Stream<_i7.User?>.empty(),
          )
          as _i4.Stream<_i7.User?>);

  @override
  _i4.Future<void> createUserProfile(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserProfile(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserProfile(_i5.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProfile, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserPoints(_i5.UserId? userId, _i8.Points? points) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPoints, [userId, points]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addPoints(_i5.UserId? userId, _i8.Points? points) =>
      (super.noSuchMethod(
            Invocation.method(#addPoints, [userId, points]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> subtractPoints(_i5.UserId? userId, _i8.Points? points) =>
      (super.noSuchMethod(
            Invocation.method(#subtractPoints, [userId, points]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
