// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9i3pa5K5R8ECfLcezD70PPJWi4VTiAfE',
    appId: '1:232697993893:web:943a0eec63d731c11c4b4c',
    messagingSenderId: '232697993893',
    projectId: 'hoque-family-chores-app',
    authDomain: 'hoque-family-chores-app.firebaseapp.com',
    storageBucket: 'hoque-family-chores-app.firebasestorage.app',
    measurementId: 'G-EKE26R1LZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-HzQtxI5BX-lIVhn6b0wmZzUFKcGHgM',
    appId: '1:232697993893:android:53f6e476701dd9361c4b4c',
    messagingSenderId: '232697993893',
    projectId: 'hoque-family-chores-app',
    storageBucket: 'hoque-family-chores-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQIXr5ugCY5AWt7FFSYyChbDA2E5gyLA',
    appId: '1:232697993893:ios:fc1dcbe6a4d09d9a1c4b4c',
    messagingSenderId: '232697993893',
    projectId: 'hoque-family-chores-app',
    storageBucket: 'hoque-family-chores-app.firebasestorage.app',
    iosBundleId: 'com.hoque.hoqueFamilyChores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQIXr5ugCY5AWt7FFSYyChbDA2E5gyLA',
    appId: '1:232697993893:ios:b281934fead2e0fe1c4b4c',
    messagingSenderId: '232697993893',
    projectId: 'hoque-family-chores-app',
    storageBucket: 'hoque-family-chores-app.firebasestorage.app',
    iosBundleId: 'com.example.hoqueFamilyChores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9i3pa5K5R8ECfLcezD70PPJWi4VTiAfE',
    appId: '1:232697993893:web:1803ba795e3b121c1c4b4c',
    messagingSenderId: '232697993893',
    projectId: 'hoque-family-chores-app',
    authDomain: 'hoque-family-chores-app.firebaseapp.com',
    storageBucket: 'hoque-family-chores-app.firebasestorage.app',
    measurementId: 'G-G76H90NNPC',
  );
}
