import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hoque_family_chores/firebase_options.dart';
import 'screens/login_screen.dart'; // Make sure this path is correct
import 'screens/registration_screen.dart'; // Make sure this path is correct
// Import the firebase options file that will be generated by FlutterFire CLI or you create manually
// For manual setu, you might not have this generated file yet, and initialization is slightly different
// For noew, we'll use the default options
// import 'firebase_options.dart'; // This is for FlutterFire CLI setup

void main() async {
  // Ensure Flutter binding are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // For Flutter CLI, you'd use:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // For manual setup without firebase_options.dart initially:
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Family Chores App',
      // For now, let's directly show LoginScreen.
      // Later, AuthenticationWrapper will handle this.
      home: LoginScreen(), // Or RegistrationScreen() to test that one
      routes: {
        // Define routes for easy navigation if you prefer
        '/login': (context) => LoginScreen(),
        '/register': (context) => RegistrationScreen(),
        // '/home': (context) => HomeScreen(),
      },
    );
  }
}
